[general]
use_nerdfont = false
album_column = false
notify = true

[theme]
playing = "red"
playing_selected = "#eeeeee"
highlight = "black"
statusbar_progress = "yellow"
cmdline = "white"
cmdline_bg = "black"

