[general]
use_nerdfont = false
album_column = false
notify = true

[theme]
playing = "red"
playing_selected = "#DCDAD5"
highlight = "BDB3A0"
statusbar_progress = "#BDB3A0"
cmdline = "#BDB3A0"
cmdline_bg = "white"

